config/routes.rb
Rails.application.routes.draw do

  get 'messages/inbox'

  get 'messages/show'

  devise_for :entrepreneurs, :controllers => {:sessions => 'sessions', :registrations => 'entrepreneurs/registrations' }
  #devise_for :advisors , :controllers => { :registrations => 'registrations' }
  devise_for :advisors , :controllers => {:sessions => 'sessions'}
  as :advisor do
    get 'advisors/edit' => 'advisors#edit_account', :as => 'edit_advisor_registration'
    put 'advisors' => 'advisors#update_account', :as => 'advisor_registration'
    get 'advisors/records' => 'advisors#records', :as => 'advisor_records'
    post 'advisors/report' => 'advisors#report', :as => 'advisor_report'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "advisors" => "advisors#index" , as: "advisors_list"
  get "entrepreneurs" => "entrepreneurs#index" , as: "entrepreneurs_list"

  get "inbox"=>"conversations#inbox",as: "inbox"
  get "sentbox"=>"conversations#sentbox",as: "sentbox"
  get "trash"=>"conversations#trash",as: "trash"
  post "send_trash"=>"conversations#send_trash",as: "send_trash"
  post "untrash"=>"conversations#untrash",as: "untrash"

  get "conversations/:id"=>"conversations#show",as: "show_conversation"

  ActiveAdmin.routes(self)

  # after  auth entrepreneur
  authenticated :entrepreneur do
    root :to => "entrepreneurs#entrepreneur_profile" , :as => "authenticated_entrepreneur_root"
  end

  #after  auth entrepreneur
  authenticated :advisor do
    root :to => "advisors#advisor_profile" , :as => "authenticated_advisor_root"
  end
  #Advisor admin views
  get "following_ideas" => "advisors#following_ideas", :as => "following_ideas"

  root 'static_pages#home'

  get 'send_notification' => 'pusher_demo#send_notification', as: 'send_notification'

  get 'advisor_logged_in' => 'advisors#is_user_advisor', as: 'is_user_advisor'

  get 'entrepreneur_logged_in' => 'entrepreneurs#is_user_entrepreneur', as: 'is_user_entrepreneur'

  get 'not_found' => 'static_pages#not_found'

  #**********************# Mailboxer routes #********************#
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  #get 'advisors/edit_profile/:id' => 'advisors#edit', as: 'advisor_edit_profile'

  #get 'advisors/:id' => 'advisors#show', as: 'advisor_show_profile'

  resources :advisors, only: [:edit, :update, :show]
  resources :entrepreneurs , only: [:edit , :update , :show]

  resources :activities

  #get 'advisors/:id/ideas/' => 'advisor_startups#list', as: 'advisor_startups'
  #get 'advisors/:id/startups/:startup_id/ideas/:idea_id' => 'advisor_startups#show', as: 'show_advisor_idea'
  #post 'advisors/:id/startups/:startup_id' => 'advisor_startups#change_startup_status', as: 'change_startup_status_advisor'

  # resources :advisor_startups , only: [:index, :show, :update]

  # resources :startups, only: [] do
  #   resources :advisor_ideas , only: [:update , :show ]
  # end

  resources :startups , only:[:show,:new,:create,:edit,:update,:index] do
    
    collection do
       get 'advisor_index'
       get 'advisor_inactive'
    end
    member do
      put 'avatar'
      put 'active_update'
    end
    resources :startup_entrepreneurs, only:[:index,:update,:create,:destroy] 

    # to ideas controller
    resources :ideas , only:[:create,:update,:edit,:show] do
      member do
        put 'avatar'
        put 'activate'
        put 'edit_drive_folder'
        put 'deactivate'
        get 'edit_registration'
        get 'new_achievement'
        delete 'achievement/:achievement_id', :to => 'ideas#delete_achievement', as: 'delete_achievement'
        get 'new_pivot'
        post 'create_pivot'
        get 'finish_process'
        post 'create_achievement'
        put 'update_registration'
        post 'advisor_follow_idea'
      end
    end
  end


  resources :idea_stages, only:[] do
    put 'update_status' , on: :member
  end

  resources :images
  
  resources :idea_activities, only:[] do
    # personalized show to avoid conflicts with will paginate
    get 'show'
    # personalized status update route
    put 'change_status'
    put 'advisor_change_status'
    # manage comments comments_controller
    resources :comments, only:[:destroy, :create, :index,:update]
    # manage artifacts idea_artifacts_controller
    resources :idea_artifacts, except:[:show] do
      put 'change_status'
    end

  end
  resources :comments , only:[:update]

  #artifact states routes
  put 'set_as_corrections' => "idea_artifacts#set_as_corrections" ,as: 'set_artifact_as_corrections'
  put 'set_as_corrected' => "idea_artifacts#set_as_corrected" ,as: 'set_artifact_as_corrected'
  put 'set_as_finished' => "idea_artifacts#set_as_finished" ,as: 'set_artifact_as_finished'

  #invitations routes
  post "invitations"=> "invitations#create", as: "invitations"
  # show external profile
    #get 'startup/:id' => 'startups#startup_profile', as: 'startup_visitor_profile'


  #general requests
  #before upload an artifact we select the type of artifact and we get access to the support file as entrepreneur
  get 'entrepreneur_get_artifact_model' => 'idea_activities#activity_model_artifact_selected' , as: 'entrepreneur_get_artifact_model'
  # get the list of activities filtered by stage
  get 'activities_list' => 'idea_activities#list_by_stage', as: 'get_activities_list'

  get 'mark_all_as_read' => "activities#mark_all_as_read"
  #swagger configuration
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

  #elastic search routes
  get 'search_entrepreneurs', to: 'search#search_entrepreneurs'
  get 'search_entrepreneurs_index', to: 'search#search_entrepreneurs_index'

  #set activity as read
  post 'activity_read', to: 'activities#read'
  get 'update_activities', to: 'activities#update_activities'
  get 'append_activities', to: 'activities#append_activities'

  #survey
  get 'survey' => 'surveys#show', :as => 'show_survey'
  post 'start_survey' => 'surveys#start', :as => 'start_survey'
  post 'qualifyStartup' => 'surveys#qualifyStartup', :as => 'qualifyStartup'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_emprende_user
  helper_method :mailbox, :conversation

  def create
    email_target = conversation_params(:email)
    user_type = conversation_params(:type)
    if user_type == 'Entrepreneur'
      recipient = Entrepreneur.find_by(email: email_target)
    elsif user_type == 'Advisor'
      recipient = Advisor.find_by(email: email_target)
    else
      return
    end
    
    conversation = current_emprende_user.send_message(recipient, *conversation_params(:body, :subject)).conversation
    if conversation
      @message = I18n.t('controllers.conversations.create.success_message')
    else
      @message = I18n.t('controllers.conversations.create.error_message')
    end
    respond_to do |format|
      format.js 
    end

  end

  def reply
    current_emprende_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation_path(conversation)
  end

  def send_trash
    ids = params[:ids]
    ids.each do |id|
      conversation_to_trash = Mailboxer::Conversation.find(id)
      conversation_to_trash.move_to_trash current_emprende_user
    end
    respond_to do |format|
      format.json { render json: {response: :ok}}
    end
  end

  def untrash
    ids = params[:ids]
    ids.each do |id|
      conversation_to_untrash = Mailboxer::Conversation.find(id)
      conversation_to_untrash.untrash current_emprende_user
    end
    respond_to do |format|
      format.json { render json: {response: :ok}}
    end
  end

  def inbox
    @inbox = mailbox.inbox.page(params[:page]).per_page(12)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def sentbox
    @sentbox = mailbox.sentbox.page(params[:page]).per_page(12)
  end
  
  def trash
    @trash = mailbox.trash.page(params[:page]).per_page(12)
  end

  def show
    @user = nil
    conversation.mark_as_read current_emprende_user
    @receipts = conversation.receipts_for(current_emprende_user).sort_by &:created_at
    if conversation.last_message.sender.deleted_at.nil?
      @user = conversation.last_message.sender
    end
  end

  private

  def mailbox
    @mailbox ||= current_emprende_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def unread_conversations_badge
    if unread_conversations.count > 0
      content_tag :span, unread_conversations.count, class: "badge pull-right badge-red"
    end
  end
  def unread_activities_badge
    if current_emprende_user.unread_activities_count > 0
      content_tag :span, current_emprende_user.unread_activities_count, class: "badge pull-right badge-red"
    end
  end
end

app/views/conversations/_conversation.html.haml
.list-group-item.row{"data-id"=>conversation.id,class: "#{'read' if conversation.is_read? current_emprende_user }"}
  .mail-box-item.checkbox.col-xs-1
    .checkbox
      %label
        %input{:type => "checkbox"}
  =link_to show_conversation_path(conversation) do
    .row
      .mail-box-item.name.col-xs-3{:style => "min-width: 120px;\r\n display: inline-block;"}
        =conversation.last_message.sender.name
        -if conversation.last_message.sender_type == "Advisor"
          %span.label.label-info
            = I18n.t('views.conversations.conversation.advisor')
      .mail-box-item.message.col-xs-5
        %strong.mail-box-subject
          =conversation.last_message.subject  
        %span.mail-box-body
          =" - #{h truncate(conversation.last_message.body, length: 50)}"
      .mail-box-item.pull-right.col-xs-2
        =conversation.last_message.created_at.strftime("%I:%M%p - %m/%d/%Y")

app/views/conversations/_conversation_modals.html.haml
=render "/conversations/message_form"
=render "/conversations/permission_request"

app/views/conversations/_form.html.haml
= simple_form_for :message, url: reply_conversation_path(conversation) do |f|
  = f.input :subject ,:as => :hidden ,:input_html => { :value => "RE: #{conversation.subject}"}
  = f.input :body,as: :text
  .form-actions
    = f.button :submit, I18n.t('views.conversations.form.reply') ,class: 'btn-primary',data: { disable_with: "Espere un momento..."} 

app/views/conversations/_message.html.haml
.panel.panel-default.message-item
  #headingOne.panel-heading{"aria-controls" => "message-#{message.id}", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#message-#{message.id}", :role => "button"}
    .panel-title.message-header
      %div.message-sender-info
        .sender-avatar
          =avatar_tag message.sender , "sender-thumb"
        .message-info
          .message-subject-header
            ="#{message.subject}:"
          .message-body-header
            ="#{h truncate(message.body,lenght: 50)} ..."
  .panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel",id: "message-#{message.id}"}
    .panel-info.container-fluid
      .sender-name
        %strong
          = I18n.t('views.conversations.message.sent_by')
        .pull-right
          .message-date
            =message.created_at.strftime("%I:%M%p - %m/%d/%Y") 
        =message.sender.name
        -if message.sender_type == "Advisor"
          %span.label.label-info.sender-label
            = I18n.t('views.conversations.message.advisor')
    .panel-body
      =message.body

app/views/conversations/_message_form.html.haml
#messageForm.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title
      .modal-body.message-body
        = form_for :conversation, url: :conversations ,remote: true , html: {id: "conversationForm"} do |f|
          .form-group
            = f.hidden_field :email
            = f.hidden_field :type
            = f.text_field :subject,required: "", placeholder: I18n.t('views.conversations.message_form.subject'), class: "form-control"
          .form-group
            = f.text_area :body,required: "", placeholder: I18n.t('views.conversations.message_form.message'), class: "form-control"
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
              = I18n.t('views.conversations.message_form.cancel')
            = f.submit I18n.t('views.conversations.message_form.send') ,class: 'btn btn-primary'
      

app/views/conversations/_permission_request.html.haml
#permissionModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#myModalLabel.modal-title
          = I18n.t('views.conversations.permission_request.title')
      .modal-body
        = I18n.t('views.conversations.permission_request.body')
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
          = I18n.t('views.conversations.permission_request.close')

app/views/conversations/_sidebar.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{class: "#{active_class_tag('inbox')}"}
    =link_to inbox_path do
      =unread_conversations_badge
      Inbox
  %li{class: "#{active_class_tag('sentbox')}"}
    =link_to  I18n.t('views.conversations.sidebar.sent'), sentbox_path
  %li{class: "#{active_class_tag('trash')}"}
    =link_to I18n.t('views.conversations.sidebar.deleted'), trash_path

app/views/conversations/create.js.erb
//$("#pushAlerts").html("<div class='alert'><%=@message%></div>");
$("#messageForm .message-body").html("<strong class='message-alert'> <%= I18n.t('views.conversations.create_js.success') %></strong>");

app/views/conversations/inbox.html.haml
.mailbox
  .row
    .col-sm-3.col-md-2
    
    .col-sm-9.col-md-10
      / Split button
      .btn-group
        %button.btn.btn-primary
          %label
            %input{:type => "checkbox",id:"all-conversations-checkbox"}
        /%button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
        /  %span Filtrar
        /  %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.inbox.all')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.inbox.none')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.inbox.read')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.inbox.unread')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.inbox.starred')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.inbox.unstarred')
      / Single button
      .btn-group
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          = I18n.t('views.conversations.inbox.options')
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a.delete-slection{:href => "#"}
              = I18n.t('views.conversations.inbox.delete_selected')
      
      %button.btn.btn-default.refresh-button
        %span.glyphicon.glyphicon-refresh
      %span#trashing-elements
        = I18n.t('views.conversations.inbox.deleting_conversations')
  %hr/
  .row
    .col-sm-3.col-md-2
      /%a.btn.btn-danger.btn-sm.btn-block{:href => "#", :role => "button"} COMPOSE
      =render "sidebar"
    .col-sm-9.col-md-10
      -if @inbox.count != 0
        #mailbox.conversations-list.tab-pane.in.active
          .list-group
            -@inbox.each do |conversation|
              =render partial: "conversation",locals: {conversation: conversation}
        =link_to "Ver anteriores mensajes", "#", id: "conversationPaginate"
        %span#loading-mailbox-ajax
          = I18n.t('views.conversations.inbox.loading')
      -else
        %h3.mailbox-message
          = I18n.t('views.conversations.inbox.no_messages')

app/views/conversations/inbox.js.erb
<%-@inbox.each do |conversation|%>
  $(".list-group").append("<%= escape_javascript(render(:partial => 'conversation',locals:{conversation: conversation})) %>")
<%-end%>

app/views/conversations/sentbox.html.haml
.mailbox
  .row
    .col-sm-3.col-md-2
      
    .col-sm-9.col-md-10
      / Split button
      .btn-group
        %button.btn.btn-primary
          %label
            %input{:type => "checkbox",id:"all-conversations-checkbox"}
        /%button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
        /  %span Filtrar
        /  %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.sentbox.all')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.sentbox.none')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.sentbox.read')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.sentbox.unread')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.sentbox.unread')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.sentbox.unstarred')
      / Single button
      .btn-group
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          = I18n.t('views.conversations.sentbox.options')
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a.delete-slection{:href => "#"}
              = I18n.t('views.conversations.sentbox.delete_selected')
      %button.btn.btn-default.refresh-button
        %span.glyphicon.glyphicon-refresh
      %span#trashing-elements
        = I18n.t('views.conversations.sentbox.deleting_conversations')
  %hr/
  .row
    .col-sm-3.col-md-2
      /%a.btn.btn-danger.btn-sm.btn-block{:href => "#", :role => "button"} COMPOSE
      =render "sidebar"
    .col-sm-9.col-md-10
      -if @sentbox.count != 0
        #mailbox.conversations-list.tab-pane.in.active
          .list-group
            -@sentbox.each do |conversation|
              =render partial: "conversation",locals: {conversation: conversation}
        =link_to I18n.t('views.conversations.sentbox.see_previous_messages'), "#", id: "conversationPaginate"
        %span#loading-mailbox-ajax
          = I18n.t('views.conversations.sentbox.loading')
      -else
        %h3.mailbox-message
          = I18n.t('views.conversations.sentbox.no_messages')

app/views/conversations/sentbox.js.erb
<%-@sentbox.each do |conversation|%>
  $(".list-group").append("<%= escape_javascript(render(:partial => 'conversation',locals:{conversation: conversation})) %>")
<%-end%>

app/views/conversations/trash.html.haml
.mailbox
  .row
    .col-sm-3.col-md-2
      
    .col-sm-9.col-md-10
      / Split button
      .btn-group
        %button.btn.btn-primary
          %label
            %input{:type => "checkbox",id:"all-conversations-checkbox"}
        /%button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
        /  %span Filtrar
        /  %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.trash.all')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.trash.none')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.trash.read')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.trash.unread')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.trash.starred')
          %li
            %a{:href => "#"}
              = I18n.t('views.conversations.trash.unstarred')
      / Single button
      .btn-group
        %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
          = I18n.t('views.conversations.trash.options')
          %span.caret
        %ul.dropdown-menu{:role => "menu"}
          %li
            %a.untrash-slection{:href => "#"}
              = I18n.t('views.conversations.trash.recover')
              
      %button.btn.btn-default.refresh-button
        %span.glyphicon.glyphicon-refresh
      %span#trashing-elements
        = I18n.t('views.conversations.trash.loading')
  %hr/
  .row
    .col-sm-3.col-md-2
      /%a.btn.btn-danger.btn-sm.btn-block{:href => "#", :role => "button"} COMPOSE
      =render "sidebar"
    .col-sm-9.col-md-10
      -if @trash.count != 0
        #trash.conversations-list.tab-pane.in.active
          .list-group
            -@trash.each do |conversation|
              =render partial: "conversation",locals: {conversation: conversation}
        =link_to I18n.t('views.conversations.trash.see_previous_messages'), "#", id: "conversationPaginate"
        %span#loading-mailbox-ajax
          = I18n.t('views.conversations.trash.loading')
      -else
        %h3.mailbox-message
          = I18n.t('views.conversations.trash.no_messages')

app/views/conversations/trash.js.erb
<%-@trash.each do |conversation|%>
  $(".list-group").append("<%= escape_javascript(render(:partial => 'conversation',locals:{conversation: conversation})) %>");
<%-end%>