config/routes.rb
Rails.application.routes.draw do

  get 'messages/inbox'

  get 'messages/show'

  devise_for :entrepreneurs, :controllers => {:sessions => 'sessions', :registrations => 'entrepreneurs/registrations' }
  #devise_for :advisors , :controllers => { :registrations => 'registrations' }
  devise_for :advisors , :controllers => {:sessions => 'sessions'}
  as :advisor do
    get 'advisors/edit' => 'advisors#edit_account', :as => 'edit_advisor_registration'
    put 'advisors' => 'advisors#update_account', :as => 'advisor_registration'
    get 'advisors/records' => 'advisors#records', :as => 'advisor_records'
    post 'advisors/report' => 'advisors#report', :as => 'advisor_report'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "advisors" => "advisors#index" , as: "advisors_list"
  get "entrepreneurs" => "entrepreneurs#index" , as: "entrepreneurs_list"

  get "inbox"=>"conversations#inbox",as: "inbox"
  get "sentbox"=>"conversations#sentbox",as: "sentbox"
  get "trash"=>"conversations#trash",as: "trash"
  post "send_trash"=>"conversations#send_trash",as: "send_trash"
  post "untrash"=>"conversations#untrash",as: "untrash"

  get "conversations/:id"=>"conversations#show",as: "show_conversation"

  ActiveAdmin.routes(self)

  # after  auth entrepreneur
  authenticated :entrepreneur do
    root :to => "entrepreneurs#entrepreneur_profile" , :as => "authenticated_entrepreneur_root"
  end

  #after  auth entrepreneur
  authenticated :advisor do
    root :to => "advisors#advisor_profile" , :as => "authenticated_advisor_root"
  end
  #Advisor admin views
  get "following_ideas" => "advisors#following_ideas", :as => "following_ideas"

  root 'static_pages#home'

  get 'send_notification' => 'pusher_demo#send_notification', as: 'send_notification'

  get 'advisor_logged_in' => 'advisors#is_user_advisor', as: 'is_user_advisor'

  get 'entrepreneur_logged_in' => 'entrepreneurs#is_user_entrepreneur', as: 'is_user_entrepreneur'

  get 'not_found' => 'static_pages#not_found'

  #**********************# Mailboxer routes #********************#
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  #get 'advisors/edit_profile/:id' => 'advisors#edit', as: 'advisor_edit_profile'

  #get 'advisors/:id' => 'advisors#show', as: 'advisor_show_profile'

  resources :advisors, only: [:edit, :update, :show]
  resources :entrepreneurs , only: [:edit , :update , :show]

  resources :activities

  #get 'advisors/:id/ideas/' => 'advisor_startups#list', as: 'advisor_startups'
  #get 'advisors/:id/startups/:startup_id/ideas/:idea_id' => 'advisor_startups#show', as: 'show_advisor_idea'
  #post 'advisors/:id/startups/:startup_id' => 'advisor_startups#change_startup_status', as: 'change_startup_status_advisor'

  # resources :advisor_startups , only: [:index, :show, :update]

  # resources :startups, only: [] do
  #   resources :advisor_ideas , only: [:update , :show ]
  # end

  resources :startups , only:[:show,:new,:create,:edit,:update,:index] do
    
    collection do
       get 'advisor_index'
       get 'advisor_inactive'
    end
    member do
      put 'avatar'
      put 'active_update'
    end
    resources :startup_entrepreneurs, only:[:index,:update,:create,:destroy] 

    # to ideas controller
    resources :ideas , only:[:create,:update,:edit,:show] do
      member do
        put 'avatar'
        put 'activate'
        put 'edit_drive_folder'
        put 'deactivate'
        get 'edit_registration'
        get 'new_achievement'
        delete 'achievement/:achievement_id', :to => 'ideas#delete_achievement', as: 'delete_achievement'
        get 'new_pivot'
        post 'create_pivot'
        get 'finish_process'
        post 'create_achievement'
        put 'update_registration'
        post 'advisor_follow_idea'
      end
    end
  end


  resources :idea_stages, only:[] do
    put 'update_status' , on: :member
  end

  resources :images
  
  resources :idea_activities, only:[] do
    # personalized show to avoid conflicts with will paginate
    get 'show'
    # personalized status update route
    put 'change_status'
    put 'advisor_change_status'
    # manage comments comments_controller
    resources :comments, only:[:destroy, :create, :index,:update]
    # manage artifacts idea_artifacts_controller
    resources :idea_artifacts, except:[:show] do
      put 'change_status'
    end

  end
  resources :comments , only:[:update]

  #artifact states routes
  put 'set_as_corrections' => "idea_artifacts#set_as_corrections" ,as: 'set_artifact_as_corrections'
  put 'set_as_corrected' => "idea_artifacts#set_as_corrected" ,as: 'set_artifact_as_corrected'
  put 'set_as_finished' => "idea_artifacts#set_as_finished" ,as: 'set_artifact_as_finished'

  #invitations routes
  post "invitations"=> "invitations#create", as: "invitations"
  # show external profile
    #get 'startup/:id' => 'startups#startup_profile', as: 'startup_visitor_profile'


  #general requests
  #before upload an artifact we select the type of artifact and we get access to the support file as entrepreneur
  get 'entrepreneur_get_artifact_model' => 'idea_activities#activity_model_artifact_selected' , as: 'entrepreneur_get_artifact_model'
  # get the list of activities filtered by stage
  get 'activities_list' => 'idea_activities#list_by_stage', as: 'get_activities_list'

  get 'mark_all_as_read' => "activities#mark_all_as_read"
  #swagger configuration
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

  #elastic search routes
  get 'search_entrepreneurs', to: 'search#search_entrepreneurs'
  get 'search_entrepreneurs_index', to: 'search#search_entrepreneurs_index'

  #set activity as read
  post 'activity_read', to: 'activities#read'
  get 'update_activities', to: 'activities#update_activities'
  get 'append_activities', to: 'activities#append_activities'

  #survey
  get 'survey' => 'surveys#show', :as => 'show_survey'
  post 'start_survey' => 'surveys#start', :as => 'start_survey'
  post 'qualifyStartup' => 'surveys#qualifyStartup', :as => 'qualifyStartup'

end

app/models/idea_activity.rb
# == Schema Information
#
# Table name: idea_activities
#
#  id                :integer          not null, primary key
#  activity_model_id :integer
#  idea_stage_id     :integer
#  status            :integer          default(0)
#  start_date        :datetime
#  due_date          :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  deadline_date     :datetime
#

class IdeaActivity < ActiveRecord::Base
  include PublicActivity::Common
  # relatives
  belongs_to :idea_stage
  has_many :idea_artifacts,-> { order(created_at: :desc) }, dependent: :destroy
  belongs_to :activity_model


  # if the status is finished or started we have to set the due date
  before_update :set_due_date

  enum status: [:pending, :start, :finish]

  def model
    activity_model
  end

  def startup
    idea_stage.idea_process.idea.startup
  end

  def idea
    idea_stage.idea_process.idea
  end

  # commentable
  acts_as_commentable

  # validations
  validates :activity_model_id, presence: true
  validates :idea_stage_id, presence: true
  validates :status, presence: true

  # method to detect if we have at least one comment
  def comments?(advisor_id)
    #  by default we don't have any comment
    if self.comment_threads.empty?
      false
    elsif self.comment_threads.where("commentable_type = ? AND user_role = ? AND user_id = ?", 'IdeaActivity', 'Advisor', advisor_id).empty?
      false
    else
      true
    end
  end

  # method to detect if we have at least one deliverable
  def artifacts?
    #  by default we don't have any comment
    if self.idea_artifacts.empty?
      false
    else
      true
    end
  end

  # method to detect if we have all the artifacts finished
  def artifacts_finished?
    # other artifact  is still unfinished ?
    if self.idea_artifacts != nil
      # binding.pry
      self.idea_artifacts.each do |artifact|
        if artifact.status == 'finish'
          # if the artifact is finished
          true
        else
          false
          break
        end
      end
    else
      true
    end
  end

  def self.activity_average(activity_model)
    total_time = 0
    activities = self.where("activity_model_id = ? AND status = ?", activity_model, 2)
    activities.each do |activity|
      total_time = total_time + TimeDifference.between(activity.start_date, activity.due_date).in_days
    end
    # calculate the average
      average = total_time / (activities.count.nonzero? || 1)
      return average
  end

  # number of ideas executing the current activity
  def self.current_ideas_number(activity_id)
    idea_processes = []
    activities = self.where("activity_model_id = ? AND status = ?", activity_id, 1)
    activities.each do |activity|
      idea_processes << activity.idea_stage.idea_process.idea_id
    end

    #remove repeated elements and count
    idea_processes = idea_processes.uniq
    return idea_processes.count
  end


  protected

  def set_due_date
    if self.status == 'finish'
      self.due_date = Time.now.in_time_zone
    elsif self.status == 'start' && self.start_date.nil?
      self.start_date = Time.now.in_time_zone
    end
  end
end

app/controllers/idea_activities_controller.rb
# == Schema Information
#
# Table name: idea_activities
#
#  id                :integer          not null, primary key
#  activity_model_id :integer
#  idea_stage_id     :integer
#  status            :integer          default(0)
#  start_date        :datetime
#  due_date          :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  deadline_date     :datetime
#

class IdeaActivitiesController < ApplicationController
  # filter actions to be user before each request
  before_action :authenticate_emprende_user
  before_action :set_activity, except: [:activity_model_artifact_selected, :list_by_stage]

  # override to both sides
  # GET show
  def show
    if entrepreneur_signed_in?
      entrepreneur_show
      render :entrepreneur_show
    elsif advisor_signed_in?
      advisor_show
      render :advisor_show
    end
  end

  # only the advisor will have the chance to modify the status of each activity.
  # insert notification
  def advisor_change_status
    respond_to do |format|
      # redirects
      format.html { redirect_to idea_activity_show_path(@activity) }
      # conditions
      if change_status_params[:status] == 'finish'
        if !@activity.comments?(current_emprende_user.id)
          # doesn't have comments
          flash[:notice] = I18n.t('controllers.idea_activities.advisor_change_status.at_least_one_comment')
        # elsif !@activity.artifacts?
          # doesn't have artifacts
          # flash[:notice] = 'no es posible finalizar la actividad si no cuenta al menos con un entregable'
        elsif !@activity.artifacts_finished?
          flash[:notice] =  I18n.t('controllers.idea_activities.advisor_change_status.all_deliverables_finished')
        else
          # everything seems to be good
          advisor_update_status(@activity, change_status_params)
        end
      else
        # you sent another status
        advisor_update_status(@activity, change_status_params)
      end
    end
  end

  # Entrepreneur only can start an activity
  # insert notification
  def change_status
    if @activity.status == 'pending'
      respond_to do |format|
        if @activity.update(status: 1)
          @activity.create_activity :update_status, owner: current_emprende_user, recipient: @idea , parameters: {idea_activity: @activity}
          format.html { redirect_to idea_activity_show_path(@activity), notice:  I18n.t('controllers.idea_activities.change_status.activity_started') }
        else
          format.html { redirect_to idea_activity_show_path(@activity), notice: I18n.t('controllers.idea_activities.change_status.activity_change_status_error')}
        end
      end
    end
  end

  # this method will return all the information related to a model artifact that
  # the entrepreneur is gonna upload as a deliverable
  def activity_model_artifact_selected
    @artifact_model = ArtifactModel.find(params[:id])
    render json: @artifact_model
  end

  def list_by_stage
    @stage = StageModel.find(params[:id])
    @activities = @stage.activity_models
    render json: @activities
  end

  # parameters
  def change_status_params
    params.require(:idea_activity).permit(:status)
  end

  private

  def set_activity
    @activity = IdeaActivity.find(params[:idea_activity_id])
    @idea = @activity.idea
    @startup = @activity.startup
  end

  # view the activity by the side of each entrepreneur
  def entrepreneur_show
    authorize! :admin, @startup
    @comments_paginated = @activity.comment_threads.order('created_at DESC').paginate(page: params[:comments_page], per_page: 4)
    # new artifact
    @new_artifact = @activity.idea_artifacts.new
    # return artifacts
    @artifacts_paginated = @activity.idea_artifacts.order('created_at DESC').paginate(page: params[:artifacts_page], per_page: 3)
    # create a new deliverable
    @new_comment = Comment.build_from(@activity,
                                      current_emprende_user.id,
                                      current_emprende_user.class,
                                      current_emprende_user_full_name,
                                      '',
                                      '')
  end

  # view the activity by the side of each advisor
  def advisor_show
    # return comments
    @comments_paginated = @activity.comment_threads.order('created_at DESC').paginate(page: params[:comments_page], per_page: 4)
    # paginate artifacts
    @artifacts_paginated = @activity.idea_artifacts.order('created_at DESC').paginate(page: params[:artifacts_page], per_page: 2)
    # generate a new comment
    @new_comment = Comment.build_from(@activity,
                                      current_emprende_user.id,
                                      current_emprende_user.class,
                                      current_emprende_user_full_name,
                                      '',
                                      '')
  end

  def advisor_update_status(activity, change_status_params)
    if activity.update(change_status_params)
      activity.create_activity :update_status, owner: current_emprende_user, recipient: @idea , parameters: {idea_activity: activity}
      flash[:notice] = I18n.t('controllers.idea_activities.advisor_update_status.change_status_success')
    else
      flash[:notice] = I18n.t('controllers.idea_activities.advisor_update_status.change_status_error')
    end
  end
end

app/helpers/idea_activities_helper.rb
# == Schema Information
#
# Table name: idea_activities
#
#  id                :integer          not null, primary key
#  activity_model_id :integer
#  idea_stage_id     :integer
#  status            :integer          default(0)
#  start_date        :datetime
#  due_date          :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  deadline_date     :datetime
#

module IdeaActivitiesHelper
  def status_icon(status)
    if status == "finish"
      image = image_tag "finish-icon.png"
    elsif status == "start"
      image = image_tag "clock-icon.png"
    end
    image
  end

  def activity_path(activity)
    if IdeaActivity.exists?(activity)
      idea_activity_show_path(activity.id)
    else
      "#"
    end
  end


end

app/views/idea_activities/_advisor_status_form.html.haml
.row
  .col-md-12
    .status-form
      = simple_form_for activity, html: { class: 'change_activity_status_form'}, :url => idea_activity_advisor_change_status_path(activity), :method => :put  do |f|
        -if activity.status == 'pending'
          - IdeaActivity.statuses.keys.each do |status|
            -if status != 'pending'  && status != 'finish'
              .row
                = f.radio_button :status, status, :class => 'radio_activity_status'
                = f.label I18n.t("views.idea_artifacts.advisor_artifact_form.status.#{status}")
        -if activity.status == 'start' || activity.status == 'finish'
          - IdeaActivity.statuses.keys.each do |status|
            -if status != 'pending'
              .row
                = f.radio_button :status, status, :class => 'radio_activity_status'
                = f.label I18n.t("views.idea_artifacts.advisor_artifact_form.status.#{status}")

app/views/idea_activities/_entrepreneur_status_form.html.haml
= simple_form_for activity, :url => idea_activity_change_status_path(activity), :method => :put do |f|
  = f.error_notification
  = f.button :submit, I18n.t('views.idea_activities.entrepreneur_status_form.start_activity'),  data: {:confirm=> I18n.t('views.idea_activities.entrepreneur_status_form.start_activity_confirmation')},class: 'btn btn-start-activity'

app/views/idea_activities/_idea_artifact.html.haml
- if idea_artifact.id != nil
  .row.idea_artifact{ :id => "idea_artifact_#{idea_artifact.id}" }
    .col-md-12
      -if @activity.status == 'start'
        - if idea_artifact.status != 'finish'
          .row
            = link_to 'x', idea_activity_idea_artifact_path(@activity,idea_artifact.id), :method => :delete , remote: true  , :class => 'close artifact_list_delete_button', :data => {:confirm =>  I18n.t('views.idea_activities.idea_artifact.remove_artifact_confirmation') }
        .row
          %h4
            = idea_artifact.name
      .row
        %p
          %strong
            = I18n.t('views.idea_activities.idea_artifact.status')
          %span.idea_artifact_status.label.label-info
            = I18n.t("activerecord.attributes.idea_artifact.artifact_status.#{idea_artifact.status}")
      .row
        %p
          %strong
            = I18n.t('views.idea_activities.idea_artifact.tags')
          - idea_artifact.tags.each do |tag|
            %span.idea_artifact_status.label.label-primary
              = tag
      - if @activity.status == 'start' && @activity.idea_stage.status == 'start'
        - if idea_artifact.status != 'finish'
          .row
            = link_to I18n.t('views.idea_activities.idea_artifact.edit'), edit_idea_activity_idea_artifact_path(@activity,idea_artifact.id) , remote: true , class: 'edit_idea_artifact_button btn btn-primary btn-sm'
      .row.attached_files
        = link_to  idea_artifact.url, target: '_blank' , class: 'google_drive_link' do
          = image_tag('drive_icon.png', class: 'artifact_drive_file_icon')
        /- if idea_artifact.support.present?
        /= link_to  idea_artifact.support.url, target: '_blank', class: 'attached_file_link'  do
        /= image_tag('file_icon.png' , class: 'artifact_file_icon')

app/views/idea_activities/_idea_artifacts_paginated.html.haml
- artifacts_paginated.each do |idea_artifact|
  /- if idea_artifact.id != nil
  .idea_artifact{ :id => "idea_artifact_#{idea_artifact.id}" }
    - if entrepreneur_signed_in?
      .col-md-12
        -if @activity.status == 'start' && @activity.idea_stage.status == 'start'
          - if idea_artifact.status != 'finish'
            .row
              = link_to 'x', idea_activity_idea_artifact_path(@activity,idea_artifact.id), :method => :delete , remote: true  , :class => 'close artifact_list_delete_button', :data => {:confirm => I18n.t('views.idea_activities.idea_artifacts_paginated.delete_confirmation')}
        .row
          %h4
            = idea_artifact.name
        .row
          %p
            %strong
              = I18n.t('views.idea_activities.idea_artifacts_paginated.status')
            %span.idea_artifact_status.label.label-info
              = I18n.t("activerecord.attributes.idea_artifact.artifact_status.#{idea_artifact.status}")
        .row
          %p
            %strong
              = I18n.t('views.idea_activities.idea_artifacts_paginated.tags')
            - idea_artifact.tags.each do |tag|
              %span.idea_artifact_status.label.label-primary
                = tag
        - if @activity.status == 'start' && @activity.idea_stage.status == 'start'
          - if idea_artifact.status != 'finish'
            .row
              = link_to I18n.t('views.idea_activities.idea_artifacts_paginated.edit') , edit_idea_activity_idea_artifact_path(@activity,idea_artifact.id) , remote: true , class: 'edit_idea_artifact_button btn btn-primary btn-sm'
        .row.attached_files
          = link_to  idea_artifact.url, target: '_blank' , class: 'google_drive_link' do
            = image_tag('drive_icon.png', class: 'artifact_drive_file_icon')
          /- if idea_artifact.support.present?
          /= link_to  idea_artifact.support.url, target: '_blank', class: 'attached_file_link'  do
          /= image_tag('file_icon.png' , class: 'artifact_file_icon')
    - if advisor_signed_in?
      .col-md-6
        .row
          %h4
            = idea_artifact.name
        .row
          %p
            %strong
              = I18n.t('views.idea_activities.idea_artifacts_paginated.tags')
            - idea_artifact.tags.each do |tag|
              %span.idea_artifact_status.label.label-primary
                = tag
        .row.attached_files
          = link_to  idea_artifact.url, target: '_blank' , class: 'google_drive_link' do
            = image_tag('drive_icon.png', class: 'artifact_drive_file_icon')
          /- if idea_artifact.support.present?
          /= link_to  idea_artifact.support.url, target: '_blank', class: 'attached_file_link'  do
          /= image_tag('file_icon.png' , class: 'artifact_file_icon')
      - if @activity.status == 'start' && @activity.idea_stage.status == 'start'
        .col-md-6
          .row
            = render partial: 'idea_artifacts/advisor_artifact_form', locals: { activity: @activity , artifact: idea_artifact}

= js_will_paginate artifacts_paginated, param_name: 'artifacts_page', :params => { :controller => 'idea_artifacts', :action => 'index'}, class: 'artifacts-pagination'

app/views/idea_activities/advisor_change_status.js.erb
$("#customAlerts").append("<div class='alert'> <%= I18n.t('views.idea_activities.advisor_change_status_js.success')%> </div>");
$(".alert").delay(2000).fadeOut(1000);

app/views/idea_activities/advisor_show.html.haml
%ol.breadcrumb
  / %li
  /   =link_to startup_path(@startup) do
  /     =@startup.name
  %li
    =link_to [@startup,@idea] do
      =@idea.name
  %li.active
    %strong
      = I18n.t('views.idea_activities.entrepreneur_show.activity')
    =link_to idea_activity_show_path @activity do
      =@activity.model.name

%section#ideaProfile.padding-right
  .idea-profile-header.activity-idea
    .row
      .col-md-6
        %h1.idea-name-title
          =@activity.model.name
          .idea-startup-name
            =avatar_mini_idea_tag @idea , "startup-mini-thumb" 
            =link_to [@startup,@idea] do
              =@idea.name
      .col-md-6
        .btn-group.idea_artifact_options{"aria-label" => "...", :role => "group"}
          =link_to [@startup,@idea] ,class: "btn btn-default" do
            .fa.fa.fa-arrow-left
            = I18n.t('views.idea_activities.entrepreneur_show.come_back_to')
            =@idea.name
          .btn-group{:role => "group"}
            %button.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
              = I18n.t('views.idea_activities.entrepreneur_show.stage_details')
              %span.caret
            %ul.dropdown-menu.stage-description
              .idea-profile-stage{class: "#{@activity.idea_stage.status}"}
                .idea-profile-sidebar-activities
                  %h5
                    = I18n.t('views.idea_activities.entrepreneur_show.stage')
                    =@activity.idea_stage.model.name
                  %ul
                    -@activity.idea_stage.idea_activities.each do |activity|
                      - if @activity.idea_stage.status == 'start' || @activity.idea_stage.status == 'finish'
                        %li{class: "#{'activity-side-active' if activity == @activity}"}
                          = link_to idea_activity_show_path(activity) , class: "activity-link-activated activity-#{activity.status}" do
                            =activity.model.name
                      -else
                        %li
                          %span.activity-link{class: "activity-#{activity.status}"}
                            = activity.model.name
  /----------------  Activity Description -----------------------/
  #activityDescription
    .row
      .col-md-8.col-md-offset-2
        .activity-content.text-center
          #idea-activity-state
            %p.idea-activity-state
              ="#{I18n.t('views.idea_activities.advisor_show.literal_activity')} #{I18n.t("activerecord.attributes.idea_activity.activity_status.#{@activity.status}")}"
            .activity-status-image
              =status_icon(@activity.status)
          #idea-activity-start-date
            #advisorOptions      
              - if @activity.idea_stage.status == 'start'
                .activity-change-status-button-div
                  = render partial: 'advisor_status_form' , locals: { activity: @activity}
            %p
              %strong
                = I18n.t('views.idea_activities.advisor_show.start_date')
              =date_formated(@activity.start_date) ||  I18n.t('views.idea_activities.advisor_show.not_defined')
          #idea-activity-due-date
            %p
              %strong
                = I18n.t('views.idea_activities.advisor_show.due_date')
              =date_formated(@activity.due_date) || I18n.t('views.idea_activities.advisor_show.not_defined')
        .activity-content
          %h3
            = I18n.t('views.idea_activities.advisor_show.description')
          %p
            = @activity.model.description
        -unless @activity.status == "finish"
          #activityRequirements.activity-content
            %h3
              = I18n.t('views.idea_activities.advisor_show.artifacts_required')
            .activity-requirement-artifacts
              -@activity.model.artifact_models.each_with_index do |artifact_model,i|
                .artifact-link-container
                  .artifact-description-name
                    ="#{i+1}. "
                    =artifact_model.name
                  .artifact-description-content
                    =artifact_model.description
                    %br
                    =link_to_if(artifact_model.support.present?, I18n.t('views.idea_activities.advisor_show.see_drive_format'), artifact_model.support.url, target: "_blank")



  /--------------- Activity body ----------------------------/
  #activityBody
    #idea-activity-body
      #activityArtifacts
        %h2
          = I18n.t('views.idea_activities.advisor_show.activity_artifacts')

  -unless @activity.status == "pending"
    #artifacts-list
      =render partial: "idea_artifacts/artifact_list", locals: {artifacts: @activity.idea_artifacts}
    #commentContainer
      .row
        .col-md-8.col-md-offset-2
          #activityComments
            %h4.text-center
              = I18n.t('views.idea_activities.advisor_show.activity')
            -# unless @activity.status == 'finish'
            = render partial: 'comments/comments_form', locals: { comment: @new_comment }
            #activity_comments_paginated
              = render partial: 'comments_paginated', locals: {comments_paginated: @comments_paginated , activity: @activity}
#backtoIdea
  =link_to startup_idea_path(@startup,@idea), class: "btn btn-default" do
    .fa.fa-arrow-left
    ="#{I18n.t('views.idea_activities.advisor_show.come_back')} #{@idea.name}"


#artifact_modal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#artifact_modal_label.modal-title
          = I18n.t('views.idea_activities.advisor_show.activity_artifact')
          =avatar_mini_idea_tag @idea , "idea-mini-thumb"
          = @idea.name
      .modal-body
        .container-fluid
          .row
            .col-md-12
              #artifact_form_errors_div
          .row
            .col-md-12
              #entrepreneur_artifact_partial
#artifactDescription.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#artifactDescriptionTitle.modal-title 
      #artifactDescriptionBody.modal-body
        \...
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
          = I18n.t('views.idea_activities.advisor_show.close')

#reportsModal.modal.fade{"aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4#exampleModalLabel.modal-title Exportar comentario
      .modal-body
        %p Desea exportar este comentario?
        = form_for :report, url: advisor_report_path , html: {id: "reportForm",target: "_blank"}  do |f|
          .form-group
            = f.hidden_field :id
            =# f.hidden_field :type
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
              = I18n.t('views.conversations.message_form.cancel')
            = f.submit "Exportar",class: 'btn btn-primary'
      