config/routes.rb
Rails.application.routes.draw do

  get 'messages/inbox'

  get 'messages/show'

  devise_for :entrepreneurs, :controllers => {:sessions => 'sessions', :registrations => 'entrepreneurs/registrations' }
  #devise_for :advisors , :controllers => { :registrations => 'registrations' }
  devise_for :advisors , :controllers => {:sessions => 'sessions'}
  as :advisor do
    get 'advisors/edit' => 'advisors#edit_account', :as => 'edit_advisor_registration'
    put 'advisors' => 'advisors#update_account', :as => 'advisor_registration'
    get 'advisors/records' => 'advisors#records', :as => 'advisor_records'
    post 'advisors/report' => 'advisors#report', :as => 'advisor_report'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "advisors" => "advisors#index" , as: "advisors_list"
  get "entrepreneurs" => "entrepreneurs#index" , as: "entrepreneurs_list"

  get "inbox"=>"conversations#inbox",as: "inbox"
  get "sentbox"=>"conversations#sentbox",as: "sentbox"
  get "trash"=>"conversations#trash",as: "trash"
  post "send_trash"=>"conversations#send_trash",as: "send_trash"
  post "untrash"=>"conversations#untrash",as: "untrash"

  get "conversations/:id"=>"conversations#show",as: "show_conversation"

  ActiveAdmin.routes(self)

  # after  auth entrepreneur
  authenticated :entrepreneur do
    root :to => "entrepreneurs#entrepreneur_profile" , :as => "authenticated_entrepreneur_root"
  end

  #after  auth entrepreneur
  authenticated :advisor do
    root :to => "advisors#advisor_profile" , :as => "authenticated_advisor_root"
  end
  #Advisor admin views
  get "following_ideas" => "advisors#following_ideas", :as => "following_ideas"

  root 'static_pages#home'

  get 'send_notification' => 'pusher_demo#send_notification', as: 'send_notification'

  get 'advisor_logged_in' => 'advisors#is_user_advisor', as: 'is_user_advisor'

  get 'entrepreneur_logged_in' => 'entrepreneurs#is_user_entrepreneur', as: 'is_user_entrepreneur'

  get 'not_found' => 'static_pages#not_found'

  #**********************# Mailboxer routes #********************#
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  #get 'advisors/edit_profile/:id' => 'advisors#edit', as: 'advisor_edit_profile'

  #get 'advisors/:id' => 'advisors#show', as: 'advisor_show_profile'

  resources :advisors, only: [:edit, :update, :show]
  resources :entrepreneurs , only: [:edit , :update , :show]

  resources :activities

  #get 'advisors/:id/ideas/' => 'advisor_startups#list', as: 'advisor_startups'
  #get 'advisors/:id/startups/:startup_id/ideas/:idea_id' => 'advisor_startups#show', as: 'show_advisor_idea'
  #post 'advisors/:id/startups/:startup_id' => 'advisor_startups#change_startup_status', as: 'change_startup_status_advisor'

  # resources :advisor_startups , only: [:index, :show, :update]

  # resources :startups, only: [] do
  #   resources :advisor_ideas , only: [:update , :show ]
  # end

  resources :startups , only:[:show,:new,:create,:edit,:update,:index] do
    
    collection do
       get 'advisor_index'
       get 'advisor_inactive'
    end
    member do
      put 'avatar'
      put 'active_update'
    end
    resources :startup_entrepreneurs, only:[:index,:update,:create,:destroy] 

    # to ideas controller
    resources :ideas , only:[:create,:update,:edit,:show] do
      member do
        put 'avatar'
        put 'activate'
        put 'edit_drive_folder'
        put 'deactivate'
        get 'edit_registration'
        get 'new_achievement'
        delete 'achievement/:achievement_id', :to => 'ideas#delete_achievement', as: 'delete_achievement'
        get 'new_pivot'
        post 'create_pivot'
        get 'finish_process'
        post 'create_achievement'
        put 'update_registration'
        post 'advisor_follow_idea'
      end
    end
  end


  resources :idea_stages, only:[] do
    put 'update_status' , on: :member
  end

  resources :images
  
  resources :idea_activities, only:[] do
    # personalized show to avoid conflicts with will paginate
    get 'show'
    # personalized status update route
    put 'change_status'
    put 'advisor_change_status'
    # manage comments comments_controller
    resources :comments, only:[:destroy, :create, :index,:update]
    # manage artifacts idea_artifacts_controller
    resources :idea_artifacts, except:[:show] do
      put 'change_status'
    end

  end
  resources :comments , only:[:update]

  #artifact states routes
  put 'set_as_corrections' => "idea_artifacts#set_as_corrections" ,as: 'set_artifact_as_corrections'
  put 'set_as_corrected' => "idea_artifacts#set_as_corrected" ,as: 'set_artifact_as_corrected'
  put 'set_as_finished' => "idea_artifacts#set_as_finished" ,as: 'set_artifact_as_finished'

  #invitations routes
  post "invitations"=> "invitations#create", as: "invitations"
  # show external profile
    #get 'startup/:id' => 'startups#startup_profile', as: 'startup_visitor_profile'


  #general requests
  #before upload an artifact we select the type of artifact and we get access to the support file as entrepreneur
  get 'entrepreneur_get_artifact_model' => 'idea_activities#activity_model_artifact_selected' , as: 'entrepreneur_get_artifact_model'
  # get the list of activities filtered by stage
  get 'activities_list' => 'idea_activities#list_by_stage', as: 'get_activities_list'

  get 'mark_all_as_read' => "activities#mark_all_as_read"
  #swagger configuration
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

  #elastic search routes
  get 'search_entrepreneurs', to: 'search#search_entrepreneurs'
  get 'search_entrepreneurs_index', to: 'search#search_entrepreneurs_index'

  #set activity as read
  post 'activity_read', to: 'activities#read'
  get 'update_activities', to: 'activities#update_activities'
  get 'append_activities', to: 'activities#append_activities'

  #survey
  get 'survey' => 'surveys#show', :as => 'show_survey'
  post 'start_survey' => 'surveys#start', :as => 'start_survey'
  post 'qualifyStartup' => 'surveys#qualifyStartup', :as => 'qualifyStartup'

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_action :authenticate_advisor!

  def show
    @questions = Question.all
    @answers = Answer.all
    @startupsAnswered = @answers.where(:answered => true, :advisor => current_advisor).group(:startup).count.values.count
    @startups = Startup.all.paginate(:page => params[:page], :per_page =>20)
    respond_to do |format|
      if @startups
        format.html
        format.js {render 'surveys/show', layout: false}
      end
    end
  end

  def qualifyStartup
    startup = Startup.find(params[:startup])
    if !params[:question].nil?
      question = Question.find(params[:question])
    end
    answer = params[:answer]

    if Integer(params[:typeSave]) == 2

      startup_has_answer = startup.answers.where(:advisor => current_advisor).first
      if startup_has_answer.nil?
        Answer.create(:startup => startup, :question => nil, :advisor => current_advisor, :answered => false, :value => nil)
      else
        startup_has_answer.destroy
      end
    else
      @answer = Answer.where(:question => question, :startup => startup, :advisor => current_advisor).limit(1)

      if @answer.empty?
        Answer.create(:startup => startup, :question => question, :advisor => current_advisor, :answered => true, :value => answer)
      else
        @answer.first.update_attribute(:value, answer)
      end

    end

    #startups calificadas por current advisor
    @startupsAnswered = Answer.all.where(:answered => true, :advisor => current_advisor).group(:startup).count.values.count
    respond_to do |format|
      format.json { render json: { "startupsAnswered" => @startupsAnswered } }
    end
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper

  def get_value_answer(startup, question, star)
    answer = startup.answers.where(question: question, advisor: current_advisor).first

    if !answer.nil? and star <= answer.value
      return true
    else
      return false
    end
  end

  def get_message_answer(startup)
    response = Hash.new
    answer = startup.answers.where(advisor: current_advisor).first

    if !answer.nil? && answer.answered
      response['msg'] = "Calificada"
      response['disabled'] = true
      response['status'] = "qualified"

    elsif !answer.nil? && !answer.answered
      response['msg'] = "La conozco"
      response['hidden'] = "hidden"
      response['status'] = "unknow"
    elsif answer.nil?
      response['msg'] ="No la conozco"
      response['status'] = "visible"
    end
    return response
  end

end

app/views/surveys/_show_startup.html.haml
%p.calificationCount
  %span#spanStartupsAnswered
    = startupsAnswered
  ="de #{startups.count} emprendimientos calificados"

-startups.each do |startup|

  .wrapCountCalifications

  .containerStartup{:id => "wrapperStartup#{startup.id}"}
    %h2.startupName.center
      =link_to startup_path(startup.id), {:target => "_blank"} do
        =startup.name
    -questions.each do |question|
      .questionCalificationGroup{class: get_message_answer(startup)['hidden']}
        .groupNameAndStars
          .questionName
            = question.name

          %form.ratingCompany{id: "ratingQuestion#{startup.id}#{question.id}"}

            %input.star-input{:type => "checkbox", checked: get_value_answer(startup, question,1), :id => "star1#{startup.id}#{question.id}", "data-question" => "#{question.id}", "data-answer" => "1",  "data-startup" => "#{startup.id}"}/
            %label.star-input-label{:for => "star1#{startup.id}#{question.id}"}
              %i.fa.fa-star
              %i.fa.fa-star.orangeStar

            %input.star-input{:type => "checkbox", checked: get_value_answer(startup, question,2), :id => "star2#{startup.id}#{question.id}", "data-question" => "#{question.id}", "data-answer" => "2",  "data-startup" => "#{startup.id}"}/
            %label.star-input-label{:for => "star2#{startup.id}#{question.id}"}
              %i.fa.fa-star
              %i.fa.fa-star.orangeStar

            %input.star-input{:type => "checkbox", checked: get_value_answer(startup, question,3), :id => "star3#{startup.id}#{question.id}", "data-question" => "#{question.id}", "data-answer" => "3",  "data-startup" => "#{startup.id}"}/
            %label.star-input-label{:for => "star3#{startup.id}#{question.id}"}
              %i.fa.fa-star
              %i.fa.fa-star.orangeStar

            %input.star-input{:type => "checkbox", checked: get_value_answer(startup, question,4), :id => "star4#{startup.id}#{question.id}", "data-question" => "#{question.id}", "data-answer" => "4",  "data-startup" => "#{startup.id}"}/
            %label.star-input-label{:for => "star4#{startup.id}#{question.id}"}
              %i.fa.fa-star
              %i.fa.fa-star.orangeStar

            %input.star-input{:type => "checkbox", checked: get_value_answer(startup, question,5), :id => "star5#{startup.id}#{question.id}", "data-question" => "#{question.id}", "data-answer" => "5",  "data-startup" => "#{startup.id}"}/
            %label.star-input-label{:for => "star5#{startup.id}#{question.id}"}
              %i.fa.fa-star
              %i.fa.fa-star.orangeStar

    .btnStartupUnknown
      %button.buttonStartupUnknown{:type => "button", :id => "buttonStartupUnknown#{startup.id}", "data-startup" => "#{startup.id}", class: get_message_answer(startup)['status'], disabled: get_message_answer(startup)['disabled']}
        = get_message_answer(startup)['msg']



.row.centerPaginate
  =js_will_paginate startups

app/views/surveys/show.html.haml
%section#surveynew
  .row
    .col-md-12
      %h2 Encuesta
  .row
    .col-md-10
      %span A continuacion podra evaluar a los emprendimientos registrados en la plataforma
      %strong Emprende CreaTIC,
      %span se evaluaran los siguientes criterios:
    .col-md-2
      =link_to show_survey_path, remote: true, id: 'start_new_survey', class: 'btn btn-width btn-default' do
        Iniciar encuesta
  .row
    .col-md-12
      - @questions.each do |question|
        %strong 
          = question.name
        %span
          = question.description
        %br/
%section#startup_survey.scrollStyle1

app/views/surveys/show.js.erb
$("#startup_survey").html("<%= j render partial: 'show_startup',locals: {startups: @startups,questions: @questions, answers: @answers,startupsAnswered: @startupsAnswered} %>");
$('#start_new_survey').fadeOut()
$('html,body').animate({
    scrollTop: $(window).scrollTop() + 300
});

$('#startup_survey').scrollTop(0);

$('.star-input').click(function () {

    $(this).parent()[0].reset();
    var prevStars = $(this).prevAll();
    var nextStars = $(this).nextAll();
    prevStars.attr('checked', true);
    nextStars.attr('checked', false);
    $(this).attr('checked', true);

    var startup = $(this).data('startup')
    var question = $(this).data('question')
    var answer = $(this).data('answer')

    startupButton = $('#buttonStartupUnknown'+startup)
    if (startupButton.hasClass('visible') || startupButton.hasClass('unknow')){
        startupButton.remove()
    }
    $.ajax({
        url: 'qualifyStartup',
        method: 'POST',
        data: {
            startup: startup,
            question: question,
            answer: answer,
            typeSave: 1
        },
        success: function(data){
            var actualAnswered = parseInt($('#spanStartupsAnswered').html());
            if (parseInt(data.startupsAnswered) !== actualAnswered){
                $('#spanStartupsAnswered').css('font-weight', "bold")
                $('#spanStartupsAnswered').html(data.startupsAnswered)

                setTimeout(function () {
                    $('#spanStartupsAnswered').css('font-weight', "normal")
                }, 1500);
            }

        }

    })
//    var spanStartupsAnswered = parseInt($('#spanStartupsAnswered').html())
//    $('#spanStartupsAnswered').html(spanStartupsAnswered + 1)

    $('body').removeClass('loading');
    $('.ajax-modal').remove()
});

$('.buttonStartupUnknown').click(function () {
    var startup = $(this).data('startup')
    if ($(this).hasClass('unknow')) {

        $('#wrapperStartup' + startup + ' .questionCalificationGroup').removeClass('hidden')
        $(this).html('No la conozco').removeClass('unknow').addClass('visible')
    } else if($(this).hasClass('visible')) {
        $('#wrapperStartup' + startup + ' .questionCalificationGroup').addClass('hidden')
        $(this).html('La conozco').removeClass('visible').addClass('unknow')
    }

    $.ajax({
        url: 'qualifyStartup',
        method: 'POST',
        data: {
            startup: startup,
            typeSave: 2
        }

    })
    $('body').removeClass('loading');
    $('.ajax-modal').remove()
});


$('.star-input-label').on('mouseover', function () {
    var prevStars = $(this).prevAll();
    prevStars.addClass('hovered');
});
$('.star-input-label').on('mouseout', function () {
    var prevStars = $(this).prevAll();
    prevStars.removeClass('hovered');
})