config/routes.rb
Rails.application.routes.draw do

  get 'messages/inbox'

  get 'messages/show'

  devise_for :entrepreneurs, :controllers => {:sessions => 'sessions', :registrations => 'entrepreneurs/registrations' }
  #devise_for :advisors , :controllers => { :registrations => 'registrations' }
  devise_for :advisors , :controllers => {:sessions => 'sessions'}
  as :advisor do
    get 'advisors/edit' => 'advisors#edit_account', :as => 'edit_advisor_registration'
    put 'advisors' => 'advisors#update_account', :as => 'advisor_registration'
    get 'advisors/records' => 'advisors#records', :as => 'advisor_records'
    post 'advisors/report' => 'advisors#report', :as => 'advisor_report'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config

  get "advisors" => "advisors#index" , as: "advisors_list"
  get "entrepreneurs" => "entrepreneurs#index" , as: "entrepreneurs_list"

  get "inbox"=>"conversations#inbox",as: "inbox"
  get "sentbox"=>"conversations#sentbox",as: "sentbox"
  get "trash"=>"conversations#trash",as: "trash"
  post "send_trash"=>"conversations#send_trash",as: "send_trash"
  post "untrash"=>"conversations#untrash",as: "untrash"

  get "conversations/:id"=>"conversations#show",as: "show_conversation"

  ActiveAdmin.routes(self)

  # after  auth entrepreneur
  authenticated :entrepreneur do
    root :to => "entrepreneurs#entrepreneur_profile" , :as => "authenticated_entrepreneur_root"
  end

  #after  auth entrepreneur
  authenticated :advisor do
    root :to => "advisors#advisor_profile" , :as => "authenticated_advisor_root"
  end
  #Advisor admin views
  get "following_ideas" => "advisors#following_ideas", :as => "following_ideas"

  root 'static_pages#home'

  get 'send_notification' => 'pusher_demo#send_notification', as: 'send_notification'

  get 'advisor_logged_in' => 'advisors#is_user_advisor', as: 'is_user_advisor'

  get 'entrepreneur_logged_in' => 'entrepreneurs#is_user_entrepreneur', as: 'is_user_entrepreneur'

  get 'not_found' => 'static_pages#not_found'

  #**********************# Mailboxer routes #********************#
  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  #get 'advisors/edit_profile/:id' => 'advisors#edit', as: 'advisor_edit_profile'

  #get 'advisors/:id' => 'advisors#show', as: 'advisor_show_profile'

  resources :advisors, only: [:edit, :update, :show]
  resources :entrepreneurs , only: [:edit , :update , :show]

  resources :activities

  #get 'advisors/:id/ideas/' => 'advisor_startups#list', as: 'advisor_startups'
  #get 'advisors/:id/startups/:startup_id/ideas/:idea_id' => 'advisor_startups#show', as: 'show_advisor_idea'
  #post 'advisors/:id/startups/:startup_id' => 'advisor_startups#change_startup_status', as: 'change_startup_status_advisor'

  # resources :advisor_startups , only: [:index, :show, :update]

  # resources :startups, only: [] do
  #   resources :advisor_ideas , only: [:update , :show ]
  # end

  resources :startups , only:[:show,:new,:create,:edit,:update,:index] do
    
    collection do
       get 'advisor_index'
       get 'advisor_inactive'
    end
    member do
      put 'avatar'
      put 'active_update'
    end
    resources :startup_entrepreneurs, only:[:index,:update,:create,:destroy] 

    # to ideas controller
    resources :ideas , only:[:create,:update,:edit,:show] do
      member do
        put 'avatar'
        put 'activate'
        put 'edit_drive_folder'
        put 'deactivate'
        get 'edit_registration'
        get 'new_achievement'
        delete 'achievement/:achievement_id', :to => 'ideas#delete_achievement', as: 'delete_achievement'
        get 'new_pivot'
        post 'create_pivot'
        get 'finish_process'
        post 'create_achievement'
        put 'update_registration'
        post 'advisor_follow_idea'
      end
    end
  end


  resources :idea_stages, only:[] do
    put 'update_status' , on: :member
  end

  resources :images
  
  resources :idea_activities, only:[] do
    # personalized show to avoid conflicts with will paginate
    get 'show'
    # personalized status update route
    put 'change_status'
    put 'advisor_change_status'
    # manage comments comments_controller
    resources :comments, only:[:destroy, :create, :index,:update]
    # manage artifacts idea_artifacts_controller
    resources :idea_artifacts, except:[:show] do
      put 'change_status'
    end

  end
  resources :comments , only:[:update]

  #artifact states routes
  put 'set_as_corrections' => "idea_artifacts#set_as_corrections" ,as: 'set_artifact_as_corrections'
  put 'set_as_corrected' => "idea_artifacts#set_as_corrected" ,as: 'set_artifact_as_corrected'
  put 'set_as_finished' => "idea_artifacts#set_as_finished" ,as: 'set_artifact_as_finished'

  #invitations routes
  post "invitations"=> "invitations#create", as: "invitations"
  # show external profile
    #get 'startup/:id' => 'startups#startup_profile', as: 'startup_visitor_profile'


  #general requests
  #before upload an artifact we select the type of artifact and we get access to the support file as entrepreneur
  get 'entrepreneur_get_artifact_model' => 'idea_activities#activity_model_artifact_selected' , as: 'entrepreneur_get_artifact_model'
  # get the list of activities filtered by stage
  get 'activities_list' => 'idea_activities#list_by_stage', as: 'get_activities_list'

  get 'mark_all_as_read' => "activities#mark_all_as_read"
  #swagger configuration
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

  #elastic search routes
  get 'search_entrepreneurs', to: 'search#search_entrepreneurs'
  get 'search_entrepreneurs_index', to: 'search#search_entrepreneurs_index'

  #set activity as read
  post 'activity_read', to: 'activities#read'
  get 'update_activities', to: 'activities#update_activities'
  get 'append_activities', to: 'activities#append_activities'

  #survey
  get 'survey' => 'surveys#show', :as => 'show_survey'
  post 'start_survey' => 'surveys#start', :as => 'start_survey'
  post 'qualifyStartup' => 'surveys#qualifyStartup', :as => 'qualifyStartup'

end

app/models/advisor.rb
# == Schema Information
#
# Table name: advisors
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  linkedin               :string
#  twitter                :string
#  facebook               :string
#  summary                :string
#  profession             :string
#  occupation             :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  deleted_at             :datetime
#  avatar                 :string
#  is_expert              :boolean          default(FALSE), not null
#  authentication_token   :string
#

class Advisor < ActiveRecord::Base
  include PublicActivity::Common
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :timeoutable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # relatives
  has_many :ideas
  has_many :answers
  # photo uploader
  # you must change :avatar to your photo attribute
  mount_uploader :avatar, AvatarUploader
  #include some tags
  acts_as_taggable
  acts_as_messageable
  acts_as_reader

  # add follower capabilities
  acts_as_follower

  # ensure a token to use the API
  before_save :ensure_authentication_token

  def ideas
    all_following
  end

  def name 
    "#{first_name} #{last_name}"
  end

  def mailboxer_email(object)
    return email
  end

  validates :first_name , presence: true , length: {minimum: 2 , maximum: 80}
  validates :last_name , presence: true , length: {minimum: 2, maximum: 80}
  validates :phone , presence: true , length: {minimum: 6 , maximum: 21}, numericality: true # , format: { with: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/ } , uniqueness: true
  validates :email , presence:true , uniqueness: true


  validates :facebook , format: {with: /(?:(?:http|https):\/\/)?(?:www.)?facebook.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[?\w\-]*\/)?(?:profile.php\?id=(?=\d.*))?([\w\-]*)?/ , allow_blank: true , message: I18n.t('activerecord.errors.models.entrepreneur.attributes.facebook.format')}
  validates :linkedin , format: {with: /(https?:)?\/\/(www\.)?linkedin.com\/(#!\/)?([^\/ ].)+/ , allow_blank: true  , message: I18n.t('activerecord.errors.models.entrepreneur.attributes.linkedin.format')}
  validates :twitter , format: {with: /(https?:)?\/\/(www\.)?twitter.com\/(#!\/)?([^\/ ].)+/ , allow_blank: true , message: I18n.t('activerecord.errors.models.entrepreneur.attributes.twitter.format')}


  validates  :summary , length: {maximum: 700}, allow_blank: true
  validates  :profession , length: {maximum: 140}, allow_blank: true
  validates  :occupation , length: {maximum: 280}, allow_blank: true


  # instead of deleting, indicate the user requested a delete & timestamp it
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end

  # ensure user account is active
  def active_for_authentication?
    super && !deleted_at
  end

  # provide a custom message for a deleted account
  def inactive_message
    !deleted_at ? super : :deleted_account
  end

  def activities
    advisor_activities_names = ['idea_stage.update_status','idea_activity.update_status','idea_activity.update_status','idea_activity.comment','idea_artifact.update_status','idea_artifact.create', 'idea.create_achievement', 'idea.delete_achievement','idea.create_pivot','idea.finish_process']
    public_activity_names = ['idea.create','startup.create']
    @activities = PublicActivity::Activity.where(key: advisor_activities_names).where(:recipient=>ideas).or(PublicActivity::Activity.where(key: public_activity_names))
    @activities.where.not('owner_id= ? AND owner_type= ?',self.id,'Advisor').where("created_at > ?", self.created_at).order('created_at DESC').limit(10)
  end

  def unread_activities_count
    activities.unread_by(self).count
  end

  def change_password(params={})
    #binding.pry
    #current_password = params.delete(:current_password) if !params[:current_password].blank?
    current_password = params[:current_password]

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end


    result = if has_no_password?  || valid_password?(current_password)
               params.delete(:current_password)
               update_attributes(params)
             else
               self.errors.add(:current_password, current_password.blank? ? :blank : :invalid)
               params.delete(:current_password)
               self.attributes = params
               false
             end

    clean_up_passwords
    result
  end

  def has_no_password?
    self.encrypted_password.blank?
  end

  # verify if there is an auth token
  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  # Generate new authentication token (a.k.a. "single access token").
  def create_authentication_token
     self.authentication_token  =  Devise.friendly_token
     self.save
     self.authentication_token
  end

  private

  #generate a new authentication token
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless Advisor.where(authentication_token: token).first
    end
  end

end

app/controllers/advisors_controller.rb
# == Schema Information
#
# Table name: advisors
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  linkedin               :string
#  twitter                :string
#  facebook               :string
#  summary                :string
#  profession             :string
#  occupation             :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  deleted_at             :datetime
#  avatar                 :string
#  is_expert              :boolean          default(FALSE), not null
#  authentication_token   :string
#

class AdvisorsController < ApplicationController

  before_action :set_advisor, only: [:edit, :update, :edit_account, :update_account, :is_user_advisor]
  before_action :authenticate_advisor! , except: [:show,:index]

  def edit
  end

  def report
    @comment = Comment.find(params['report']['id'])
    @activity = @comment.commentable
    @advisor = Advisor.find(@comment.user_id)
    render pdf: "report" , layout: 'report'  # Excluding ".pdf" extension.
  end

  def index
    @advisors = Advisor.all
  end

  def advisor_profile
    redirect_to current_advisor
  end

  def edit_account
  end

  def update
    respond_to do |format|
      if @advisor.update(advisor_params)
        format.html {redirect_to advisor_path(@advisor)}
        format.js
      else
        format.html {render :edit, notice: I18n.t('advisor.controller.uptade.error_message')}
      end
    end
  end

  def update_account
    if @advisor.change_password(advisor_params)
      sign_in @advisor , :bypass => true
      flash[:success] = 'Advisor updated'
      redirect_to advisor_path(@advisor)
      else
        render :edit_account, notice: I18n.t('advisor.controller.update_account.error_message')
      end
  end

  def show
    @advisor = Advisor.find(params[:id])
  end

  def all_startups
  end

  def following_ideas
    @active_following_ideas = []
    @unactive_following_ideas = []
    current_advisor.all_following.each do |idea|
      @active_following_ideas << idea if idea.is_active?  == true
      @unactive_following_ideas << idea if idea.is_active? == false
    end
  end

  def records
    @activity_records = PublicActivity::Activity.where(owner: current_advisor)
  end

  def advisor_params
    params.require(:advisor).permit(:id,
                                    :phone,
                                    :first_name,
                                    :last_name,
                                    :facebook,
                                    :linkedin,
                                    :twitter,
                                    :summary,
                                    :profession,
                                    :tag_list,
                                    :avatar,
                                    :occupation,
                                    :email,
                                    :current_password,
                                    :password,
                                    :password_confirmation)
  end

  def set_advisor
    @advisor = Advisor.find(current_advisor)
  end

  def is_user_advisor
    respond_to do |format|
      format.json { render json: @advisor.to_json }
    end
  end

end

app/helpers/advisors_helper.rb
# == Schema Information
#
# Table name: advisors
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  linkedin               :string
#  twitter                :string
#  facebook               :string
#  summary                :string
#  profession             :string
#  occupation             :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  deleted_at             :datetime
#  avatar                 :string
#  is_expert              :boolean          default(FALSE), not null
#  authentication_token   :string
#

module AdvisorsHelper
  def advisor_message_button(advisor)
    unless current_advisor == advisor
      button_tag "Enviar Mensaje", class: "btn btn-default btn-width" ,"data-target" => "#messageForm", "data-toggle" => "modal", "data-type" => "Advisor", "data-email" => advisor.email , :type => "button","data-name"=>advisor.name 
    end
  end
  def advisor_is_owner_of(comment)
    if current_emprende_user.class.name == "Advisor" && comment.user_id == current_emprende_user.id
      return true
    end
  end
end

app/views/advisors/_unactive_idea.html.haml
.div{id: "unactive-idea-#{idea.id}"}
  %li.unactive-idea
    %a{"aria-controls" => "idea-details-#{idea.id}", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#idea-details-#{idea.id}", :role => "button"}
      .glyphicon.fa.fa-caret-square-o-down
    %p
      =idea.name
      .idea-edit-options
        =link_to I18n.t('views.advisors.unactive_idea.see_idea'), startup_idea_path(idea.startup,idea), class: "btn btn-default"

  .unactive-collapse.collapse{id:"idea-details-#{idea.id}"}
    .well.unactive-idea-collapse
      %p
        %strong
          = I18n.t('views.advisors.unactive_idea.type')
        =idea.idea_type.capitalize
      %p
        %strong
          = I18n.t('views.advisors.unactive_idea.description')
        =idea.description
      %br
      %p
        %strong
          = I18n.t('views.advisors.unactive_idea.problem_definition')
        =idea.problem_definition

app/views/advisors/edit.html.haml
%section
  .wp-section
    .row
      .col-md-12
        .wp-block.default.user-form
          .form-header
            %h2
              = I18n.t('views.advisors.edit.headline')
          .form-body
            = simple_form_for (@advisor),html:{id: "advisorAvatarForm"} do |f|
              %fieldset
                %section
                  .form-group
                    = f.input :avatar , as: :file, :hint => avatar_tag(f.object,'avatar')
            =link_to I18n.t('views.advisors.edit.upload_image'), "#",class: "btn btn-default btn-width", id: "advisorAvatarlink"

            = simple_form_for (@advisor) do |f|
              = f.error_notification
              = f.input :first_name
              = f.input :last_name
              = f.input :phone
              = f.input :profession
              = f.input :occupation
              = f.input :summary, as: :text
              /= f.input :tag_list, label: I18n.t('views.advisors.edit.form.tag_list')
              = f.input :facebook
              = f.input :linkedin
              = f.input :twitter
              .center-align
                = f.button :submit, I18n.t('views.advisors.edit.save_changes'), class: "btn btn-width btn-primary"

app/views/advisors/edit_account.html.haml
#configAdvisorAccount
  .container
    .row
      .col-md-5.col-md-offset-2
        %section.slice.bg-white
          .wp-section
            .wp-block.default.user-form
              .form-header
                %h2
                  = I18n.t('views.advisors.registrations.edit.change_password')
              .form-body
                = simple_form_for(@advisor, url: advisor_registration_path(@advisor), html: { method: :put }) do |f|
                  = f.error_notification
                  .form-inputs
                    =# f.input :email, required: true, autofocus: true
                    = f.input :password, autocomplete: "off", hint: I18n.t('views.advisors.edit_account.leave_blank'), required: false
                    = f.input :password_confirmation, required: false
                    = f.input :current_password, hint: I18n.t('views.advisors.edit_account.current_password') , required: true
                  .center-align
                    = f.button :submit, I18n.t('views.advisors.registrations.edit.save_changes'), class: "btn-width btn btn-default"

app/views/advisors/following_ideas.html.haml
%section#avisorStartupIndex
  %h2
    = I18n.t('views.advisors.following_ideas.following_ideas')
  %section.entrepreneur-ideas-profile
    -@active_following_ideas.each do |idea|
      =render partial: "ideas/active_idea", locals: {idea: idea}

-if @unactive_following_ideas.any?
  %strong
    = I18n.t('views.advisors.following_ideas.inactive_ideas')
  %ul.unactive-ideas#unactiveIdeasList
    -@unactive_following_ideas.each do |idea|
      =render partial: "advisors/unactive_idea", locals: {idea: idea}

app/views/advisors/index.html.haml
#indexAdvisors
  %h3 Asesores 
  .container-fluid
    #entrepreneuerList
      .row
        -@advisors.each do |advisor|
          .col-sm-4
            .container-fluid
              .entrepreneur-item
                .col-xs-3
                  .entrepreneur-image-container
                    =avatar_tag(advisor,"circular")
                .col-xs-9
                  .entrepreneur-content-container
                    .name
                      =advisor.name

                    - if allow_manage_advisor?(advisor)
                      = link_to I18n.t('views.entrepreneurs.index.go_to_my_profile'), advisor, class: "btn-link"
                    -else
                      = link_to "Ver perfil", advisor, class: "btn-link"
                      %button.btn-message-index{"data-target" => "#messageForm", "data-toggle" => "modal", "data-type" => "Advisor", "data-email" => advisor.email , :type => "button","data-name"=>advisor.name}
                        = I18n.t('views.entrepreneurs.index.send_message')
                      %br
                     

/ .col-xs-12.col-sm-offset-3.col-sm-6
/   .panel.panel-default
/     .panel-heading.c-list
/       %span.title
/         = I18n.t('views.advisors.index.headline')
/     %ul#contact-list.list-group
/       -@advisors.each do |advisor|
/         %li.list-group-item
/           .col-xs-12.col-sm-3
/             =avatar_tag(advisor,"circular")
/           .col-xs-12.col-sm-9
/             %span.name 
/               =advisor.name
/             %br/
/             - if allow_manage_advisor?(advisor)
/               = link_to I18n.t('views.advisors.index.go_to_my_profile'), advisor, class: "btn btn-info"
/             -else
/               %button.btn.btn-default.btn-message{"data-target" => "#messageForm", "data-toggle" => "modal", "data-type" => "Advisor", "data-email" => advisor.email , :type => "button","data-name"=>advisor.name}
/                 = I18n.t('views.advisors.index.send_message')
/           .clearfix
=render "/conversations/conversation_modals"

app/views/advisors/records.html.haml
%section#activivitiesList
  %h1 Mi actividad como asesor
%br
  #notificationsList
    - @activity_records.each do |activity|
      .notification-container
        =render_activity(activity, fallback: 'default')
  =#will_paginate @activities
    

app/views/advisors/report.html.haml
#AdvisorReports
  .advisor-reports
    %table.table.table-bordered
      %tbody
        %tr
          %td.table-logo.text-center 
            =image_tag wicked_pdf_asset_base64("logo-purple.png")
          %td.text-center 
            %h5 
              PROCESO CREACIÓN DE STARTUPS 
              %br
              ACTA DE REUNION
          %td
            Version: 1
            %br
            Fecha: 28/10/2015
    
    .data-reports
      .row
        .col-sm-3
          %h5
            %strong Fecha:
            =@comment.reported_at_formated

      .row
        .col-sm-12
          %h5 
            %strong Emprendimiento:
            ="#{@activity.startup.name} - #{@activity.idea.name}"
          %h5 
            %strong Tema:
            ="#{}: Actividad #{@activity.model.name}"
    



  .subject-reports
    %table.table.table-bordered
      %thead
        %tr
          %th.text-center Temas tratados 
      %tbody
        %tr
          %td
            %p.body-report
              =@comment.body

  %h4 Asistentes
  .attendant-reports
    %table.table.table-bordered
      %thead
        %tr
          %th.text-center Nombre 
          %th.text-center Cédula 
          %th.text-center Entidad 
          %th.text-center Firma 
      %tbody
        %tr
          %td
            =@comment.user_name
          %td
          %td Creatic
          %td 
        -5.times do 
          %tr
            %td
              %p.assistant-report
            %td
            %td 
            %td
        

app/views/advisors/show.html.haml
%section#advisorProfile.padding-right.startup-padding-top
  .fb-profile
    .advisor-profile-cover
      .advisor-profile-cover-color
      %h2.title-header.advisor-header
        = I18n.t('views.advisors.show.advisor')
      %h1.user-name
        =@advisor.name
    .user-profile-cover-div

  %section.user-info
    .row
      .col-sm-3 
        .user-image-profile
          =avatar_tag @advisor , "fb-image-user-profile thumbnail"
        .text-center
          -if @advisor == current_emprende_user
            =link_to edit_advisor_path, class: "btn btn-primary btn-width" do
              .fa.fa-edit
              = I18n.t('views.advisors.show.edit_profile')
          =advisor_message_button(@advisor)
      .col-sm-4
        .user-info-profile
          %p
            %strong
              = I18n.t('views.advisors.show.email')
            =@advisor.email
          %p
            %strong
              = I18n.t('views.advisors.show.profession')
            =@advisor.profession
          %p
            %strong
              = I18n.t('views.advisors.show.occupation')
            =@advisor.occupation
        
      .col-sm-5
        .user-info-profile
          - if !@advisor.linkedin.nil?
            - if !@advisor.linkedin.empty?
              = link_to @advisor.linkedin, target: "_blank" do
                %p
                  %strong
                    %span.fa.fa-linkedin
                    LinkedIn
          - if !@advisor.twitter.nil?
            - if !@advisor.twitter.empty?
              = link_to @advisor.twitter, target: "_blank" do
                %p
                  %strong
                    %span.fa.fa-twitter
                    Twitter
          - if !@advisor.facebook.nil?
            - if !@advisor.facebook.empty?
              = link_to @advisor.facebook, target: "_blank" do
                %p
                  %strong
                    %span.fa.fa-facebook
                    Facebook
        

#advisorInfo
  .container-fluid
    .col-md-8.col-md-offset-2
      .advisor-bio
        %h3.text-center
          = I18n.t('views.advisors.show.about')
          =@advisor.first_name
        %p
          =@advisor.summary

=render "/conversations/conversation_modals"